site_name: AWS Solutions Architect Learning Path
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit

repo_url: https://github.com/VM-137/AWS-examples
repo_name: GitHub
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Terraform Modules:
      - API: 
        - STS: api/sts/index.md
      - S3:
        - ACLs: s3/acls/index.md
        - Bucket Policies: s3/bucket-Policies/index.md
        - Checksums: s3/checksums/index.md 
        - Cors: s3/cors/index.md
        - Encryption:
          - Server-Side: s3/encryption/index.md
          - Client-Side: s3/encryption-client-site/index.md
        - Metadata: s3/metadata/index.md
        - Prefixes: s3/prefixes/index.md
        - Storage Classes: s3/storage-classes/index.md
      - VPC:
        - Basics: vpc/basics/index.md
        - NACLs: vpc/nacl/index.md