#!/usr/bin/env bash

# This script lists objects in an S3 bucket.
echo "Listing objects in bucket..."

if [ "$#" -ne 1 ]; then
    echo "There needs to be a bucket name. Usage: $0 <bucket_name>"
    exit 1
fi
aws s3api list-objects-v2 \
    --bucket "$1" \
    --output text

if [ $? -eq 0 ]; then
    echo "Objects listed successfully in bucket '$1'."
else
    echo "Failed to list objects in bucket '$1'."
    exit 1
fi