#!/usr/bin/env bash

echo "Deploy s3 bucket via CFN"

# ref https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy.html

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
  --template-file template.yaml \
  --no-execute-changeset \
  --stack-name $STACK_NAME \
  --region eu-west-3 
  