site_name: AWS Solutions Architect Learning Path
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit

repo_url: https://github.com/VM-137/AWS-examples
repo_name: GitHub
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Terraform Modules:
      - VPC:
        - Basics: vpc/README.md